name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      # Force offline path
      EMBED_BACKEND: "mock"
      OPENAI_API_KEY: "test-dummy"
      LLM_MODEL: "gpt-4o-mini"
      EMBED_MODEL: "text-embedding-3-small"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel setuptools
          pip install fastapi uvicorn pydantic numpy pandas scikit-learn faiss-cpu tiktoken ragas datasets nltk pyyaml rich loguru typer httpx orjson openai tenacity black ruff mypy pytest pytest-cov

      - name: Lint
        run: |
          black --check .
          ruff check .

      - name: Type check
        run: mypy src/agentic_rag -q

      - name: Unit tests (no network)
        run: pytest -q -m "not slow and not e2e" --maxfail=1
